# =============================================================================
# 剧本分镜智能体 - 动作时长估算配置
# 用途：将自然语言动作描述转换为秒级时长（用于5秒分镜切分）
# 版本：1.2
# 最后更新：2025-10-24
# =============================================================================

version: "1.2"
description: "Action duration estimation rules for storyboard segmentation"

# -----------------------------------------------------------------------------
# 1. 基础动作时长（单位：秒）
# 格式：动词/短语 → 默认时长
# 注意：优先匹配长词（如“拿起手机”优于“拿起”）
# -----------------------------------------------------------------------------
base_actions:
  # === 身体移动 ===
  走: 2.0
  快走: 1.5
  跑: 1.2
  小跑: 1.4
  起身: 1.5
  坐下: 1.3
  躺下: 1.8
  站立: 0.5
  转身: 0.8
  踱步: 2.5
  跳跃: 1.0
  蹲下: 1.2
  爬起: 1.6

  # === 手部/交互动作 ===
  伸手: 0.9
  握手: 1.2
  拥抱: 2.5
  推: 0.7
  拉: 0.7
  拿起: 1.0
  放下: 0.8
  打开: 1.0
  关闭: 0.9
  推门: 1.1
  关门: 1.0
  按按钮: 0.6
  拨号: 1.2
  接听电话: 1.0
  挂断电话: 0.8
  翻书: 1.0
  写字: 1.5
  喝水: 1.8
  吃东西: 2.0

  # === 头部/面部动作 ===
  抬头: 0.5
  低头: 0.5
  转头: 0.6
  点头: 0.6
  摇头: 0.7
  微笑: 0.8
  大笑: 1.2
  皱眉: 0.6
  瞪眼: 0.5
  闭眼: 0.4
  流泪: 1.5
  擦眼泪: 1.2
  愣住: 1.0
  犹豫: 1.2
  惊讶: 0.7
  害怕: 0.9
  生气: 0.8

  # === 特殊状态（持续性）===
  站着不动: 1.0
  坐着不动: 1.0
  凝视: 1.5
  发呆: 2.0

# -----------------------------------------------------------------------------
# 2. 修饰词修正系数（乘法因子）
# 作用于基础动作时长
# -----------------------------------------------------------------------------
modifiers:
  # 速度修饰
  快速: 0.7
  迅速: 0.65
  急速: 0.6
  飞快: 0.55
  缓缓: 1.8
  慢慢: 1.7
  轻轻: 1.3
  轻柔: 1.4
  猛地: 0.6
  突然: 0.7
  用力: 0.9
  小心: 1.2
  紧张地: 1.1
  平静地: 0.95
  激动地: 1.15
  犹豫地: 1.3

# -----------------------------------------------------------------------------
# 3. 对话时长模型
# 中文口语平均 2.8~3.5 字/秒，此处取 0.35 秒/字（含停顿）
# -----------------------------------------------------------------------------
dialogue:
  # 基础参数
  base_per_char: 0.35          # 每个中文字符基础时长（秒）
  min_duration: 1.5            # 最短对话时长（即使只有1个字）
  max_duration: 6.0            # 最长单句对话（超长需切分）

  # 情绪/语气修正系数（乘法）
  emotion_multipliers:
    默认: 1.0
    平静: 1.0
    轻声: 1.3      # 说得慢
    低声: 1.3
    大声: 0.9      # 说得快
    大喊: 0.85
    激动: 1.2
    结巴: 1.6
    哭泣: 1.4
    微笑: 0.95
    讽刺: 1.1
    疑惑: 1.2

# -----------------------------------------------------------------------------
# 4. 角色类型速度因子（可选）
# 用于根据角色属性调整整体动作速度
# 在角色 appearance 中标注 type: "elder" 等
# -----------------------------------------------------------------------------
character_speed_factors:
  default: 1.0
  child: 0.85      # 孩子动作快
  elder: 1.3       # 老人动作慢
  injured: 1.5     # 受伤角色
  athlete: 0.8     # 运动员
  robot: 0.7       # 机械动作快

# -----------------------------------------------------------------------------
# 5. 分镜切分策略
# -----------------------------------------------------------------------------
segmentation:
  target_duration: 5.0    # 目标每段时长（秒）
  max_buffer: 0.5         # 允许超出的缓冲时间（秒）
  min_action_duration: 0.4 # 单动作最短时长（防过切）