# =============================================================================
# 剧本分镜智能体 - 剧本解析配置
# 用途：配置剧本解析所需的正则表达式模式、关键词映射和分类规则
# 版本：1.0
# 最后更新：2025-10-25
# =============================================================================

version: "1.0"
description: "Script parsing configuration for storyboard generation"

# ----------------------------------------------------------------------------- # 1. 场景识别模式
# 用于提取剧本中的场景信息（地点和时间）
# -----------------------------------------------------------------------------
scene_patterns:
  - '场景[:：]\s*([^，。；\n]+)[，。；]\s*([^，。；\n]+)'
  - '地点[:：]\s*([^，。；\n]+)[，。；]\s*时间[:：]\s*([^，。；\n]+)'
  - '([^，。；\n]+)[，。；]\s*([^，。；\n]+)\s*[的]?场景'

# ----------------------------------------------------------------------------- # 2. 角色对话模式
# 用于识别剧本中的角色对话
# -----------------------------------------------------------------------------
dialogue_patterns:
  - '([^：]+)[:：]\s*(.+)\$'
  - '([^（）]+)[（(]([^)）]+)[)）][:：]\s*(.+)'

# ----------------------------------------------------------------------------- # 3. 动作情绪映射表
# 动作关键词与对应默认情绪的映射关系
# -----------------------------------------------------------------------------
action_emotion_map:
  # === 移动类动作 ===
  "走": "平静"
  "行走": "平静"
  "漫步": "轻松"
  "散步": "悠闲"
  "跑": "匆忙"
  "奔跑": "紧急"
  "冲刺": "紧张"
  "追赶": "紧迫"
  "跳": "兴奋"
  "跳跃": "高兴"
  "蹦跳": "欢快"
  "跌倒": "惊讶"
  "爬": "努力"
  "攀爬": "专注"
  "站立": "平静"
  "坐下": "放松"
  "躺": "放松"
  "躺下": "放松"
  "蹲": "谨慎"
  "弯腰": "专注"
  
  # === 表情类动作 ===
  "笑": "开心"
  "微笑": "愉悦"
  "大笑": "欢乐"
  "苦笑": "无奈"
  "哭": "悲伤"
  "流泪": "伤心"
  "抽泣": "难过"
  "嚎啕": "悲痛"
  "皱眉": "困惑"
  "蹙眉": "烦恼"
  "眯眼": "怀疑"
  "瞪眼": "愤怒"
  "挑眉": "惊讶"
  "抿嘴": "紧张"
  "咬牙": "愤怒"
  "张嘴": "惊讶"
  
  # === 情绪类动作 ===
  "颤抖": "恐惧"
  "发抖": "害怕"
  "哆嗦": "恐惧"
  "紧张": "紧张"
  "冷静": "平静"
  "镇定": "从容"
  "焦虑": "担忧"
  "担忧": "担心"
  "思考": "专注"
  "沉思": "认真"
  "发呆": "迷茫"
  "愣住": "震惊"
  "生气": "愤怒"
  "恼火": "愤怒"
  "激动": "兴奋"
  "兴奋": "高兴"
  
  # === 互动类动作 ===
  "拥抱": "亲切"
  "握手": "友好"
  "挥手": "告别"
  "点头": "同意"
  "摇头": "拒绝"
  "指向": "指示"
  "抚摸": "温柔"
  "拍打": "亲昵"
  "抓住": "急切"
  "放开": "释然"
  "推": "排斥"
  "拉": "挽留"
  
  # === 物体操作类动作 ===
  "拿起": "行动"
  "放下": "完成"
  "打开": "行动"
  "关闭": "结束"
  "翻阅": "专注"
  "书写": "认真"
  "查看": "关注"
  "观察": "仔细"
  "接听": "专注"
  "拨打": "行动"
  "使用": "专注"
  "操作": "认真"

# ----------------------------------------------------------------------------- # 4. 时间关键词映射
# 常见时间词汇的标准化映射
# -----------------------------------------------------------------------------
time_keywords:
  "早上": "早晨"
  "早晨": "早晨"
  "清晨": "清晨"
  "上午": "上午"
  "中午": "中午"
  "下午": "下午"
  "傍晚": "傍晚"
  "晚上": "晚上"
  "夜晚": "夜晚"
  "深夜": "深夜"
  "凌晨": "凌晨"
  "黎明": "黎明"
  "白天": "白天"
  "日间": "白天"
  "黑夜": "夜晚"
  "夜间": "夜晚"

# ----------------------------------------------------------------------------- # 5. 角色外观关键词
# 用于推断角色外观特征的关键词映射
# -----------------------------------------------------------------------------
appearance_keywords:
  # === 着装 ===
  "西装": "穿着正式西装"
  "正装": "穿着正式服装"
  "职业装": "穿着职业装"
  "休闲装": "穿着休闲服装"
  "T恤": "穿着T恤"
  "牛仔裤": "穿着牛仔裤"
  "长裙": "穿着长裙"
  "短裙": "穿着短裙"
  "运动服": "穿着运动服"
  
  # === 年龄/性别 ===
  "老人": "年长的"
  "年轻人": "年轻的"
  "小孩": "年幼的"
  "男人": "男性"
  "女人": "女性"
  "男孩": "男性少年"
  "女孩": "女性少年"
  
  # === 体型/外貌 ===
  "高大": "身材高大"
  "矮小": "身材矮小"
  "肥胖": "体型肥胖"
  "瘦弱": "体型瘦弱"
  "美丽": "长相美丽"
  "帅气": "长相帅气"
  "普通": "长相普通"
  "丑陋": "长相丑陋"

# ----------------------------------------------------------------------------- # 6. 地点关键词映射
# 常见地点词汇的标准化映射
# -----------------------------------------------------------------------------
location_keywords:
  # === 室内地点 ===
  "咖啡馆": "咖啡馆"
  "餐厅": "餐厅"
  "办公室": "办公室"
  "会议室": "会议室"
  "客厅": "客厅"
  "卧室": "卧室"
  "书房": "书房"
  "厨房": "厨房"
  "浴室": "浴室"
  "洗手间": "洗手间"
  "医院": "医院"
  "学校": "学校"
  "教室": "教室"
  "图书馆": "图书馆"
  "电影院": "电影院"
  "商场": "商场"
  "超市": "超市"
  "银行": "银行"
  "酒店": "酒店"
  "旅馆": "旅馆"
  "网吧": "网吧"
  "健身房": "健身房"
  "瑜伽馆": "瑜伽馆"
  "游泳池": "游泳池"
  "体育馆": "体育馆"
  
  # === 室外地点 ===
  "公园": "公园"
  "街道": "街道"
  "马路": "马路"
  "广场": "广场"
  "车站": "车站"
  "机场": "机场"
  "码头": "码头"
  "海滩": "海滩"
  "湖边": "湖边"
  "河边": "河边"
  "山顶": "山顶"
  "山脚": "山脚"
  "森林": "森林"
  "草地": "草地"
  "操场": "操场"
  "球场": "球场"
  "花园": "花园"
  "小区": "小区"
  "停车场": "停车场"

# ----------------------------------------------------------------------------- # 7. 情绪关键词扩展
# 用于情绪识别的扩展关键词
# -----------------------------------------------------------------------------
emotion_keywords:
  "喜悦": ["开心", "高兴", "欢乐", "愉悦", "欢快", "兴奋"]
  "悲伤": ["伤心", "难过", "悲痛", "无奈", "迷茫", "失落"]
  "愤怒": ["生气", "恼火", "愤怒", "不满", "排斥", "厌恶"]
  "恐惧": ["恐惧", "害怕", "紧张", "担忧", "担心", "焦虑"]
  "惊讶": ["惊讶", "震惊", "意外", "困惑", "怀疑", "疑惑"]
  "平静": ["平静", "从容", "放松", "悠闲", "轻松", "镇定"]
  "其他": ["行动", "完成", "专注", "认真", "仔细", "亲切", "友好", "同意", "拒绝", "指示", "温柔", "亲昵", "急切", "释然", "挽留", "关注", "结束"]

# ----------------------------------------------------------------------------- # 8. 场景氛围关键词
# 用于推断场景氛围的关键词
# -----------------------------------------------------------------------------
atmosphere_keywords:
  "温馨": ["温暖", "舒适", "柔和", "亲切", "安宁", "平静", "温馨"]
  "紧张": ["紧张", "紧迫", "焦虑", "担忧", "害怕", "恐惧", "不安", "忐忑"]
  "欢乐": ["开心", "高兴", "欢乐", "愉悦", "欢快", "兴奋", "热闹", "活跃"]
  "悲伤": ["伤心", "难过", "悲痛", "无奈", "迷茫", "失落", "沉重", "压抑"]
  "浪漫": ["浪漫", "温馨", "甜蜜", "幸福", "柔情", "温柔", "恩爱", "亲密"]
  "神秘": ["神秘", "诡异", "奇怪", "疑惑", "怀疑", "未知", "不确定", "朦胧"]
  "严肃": ["严肃", "认真", "庄重", "正式", "严厉", "严格", "紧张", "压抑"]
  "轻松": ["轻松", "悠闲", "自在", "舒适", "愉快", "放松", "随意", "惬意"]